yarnPath: "./.yarn/releases/yarn-berry.js"

nodeLinker: node-modules

# Workaround for jss-plugin-rule-value-function
packageExtensions:
  "jss-plugin-rule-value-function@*":
    peerDependenciesMeta:
      "tiny-warning":
        optional: true
