name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: report
          root_file: main.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: main.pdf
          path: report/main.pdf
